### PR TITLE
Add bank account details below support us form

### PR DESCRIPTION
**Pull request by gonaumov**
## Motivation and context

In order to ease the customers to support the organization we can add our bank details below the support us form on /support page

## Screenshots:

| Before              | After              |
| ------------------- | ------------------ |
| before screenshot|  after screenshot|

### CODE REVIEW

**Comment by kachar** [comment]
@swolf86 can you please review the outcome of the pr

**Comment by swolf86** [comment]
Great idea. 
2 wireframes options adding the bank details on the support us page 

https://www.figma.com/file/sUoAXcjtaQrwQfWRFF8Ych/Info-podkrepi-ni-flow?node-id=0%3A1

image
image

**Comment by gonaumov** [comment]
OK. I will change the layout.

**Comment by gonaumov** [comment]
@kachar , @swolf86 I re-implemented the layout and added possibility the iban to be copied to the clipboard via button. Please review it again.

**Comment by kachar** [comment]
I did some updates on the visuals of the support form so it looks like this now:



I think the remarks you mention are being faced in the new version

**Comment by swolf86** [comment]
Мисля че копирай би следвало да е на нивото на кода за копиране - т.е 2 реда по долу. 
Също бих подрванил 2та бутона в дясно, т.е копирай да се подравни в дясно с напред

**Pull request merged**
