### PR TITLE
Fixed bankaccounts panel mistakes in translations

### PR DESCRIPTION
**Pull request by PepiPetrov**
Fixed bankaccounts panel mistakes in translations according to @Polina1985's issue

### CODE REVIEW

**Comment by Polina1985** [comment]
@PepiPetrov 
Hello, 
I have accessed the admin panel/ Menu "Плащания" and according to my observations - nothing happened, nothing has been changed or fixed. Please, verify if the problem is to be fixed later or It has to be ready at the moment?

**Comment by PepiPetrov** [comment]
You must download the code from branch [administrative-panel/-menu-плащания](https://github.com/podkrepi-bg/frontend/tree/administrative-panel/-menu-%D0%BF%D0%BB%D0%B0%D1%89%D0%B0%D0%BD%D0%B8%D1%8F)

**Comment by Polina1985** [comment]
Hello again,
I think that I won't be able to do that. Still no understanding of code :)
So could you please do it and fix it for me. None of my business is this :) :) 
Really, I am impressed that you know so much at that age. 

With 2 words. What did you change in this ticket in order to work properly? Cause I cannot read the code.
Thanks.@

**Comment by PepiPetrov** [comment]
I changed some of the bankaccounts entity translations.

**Comment by kachar** [comment]
@Polina1985 This code still hasn't been reviewed. merged and deployed.

Once that happens I'll let you know

**Comment by Polina1985** [comment]
Ok. Thanks.

**Comment by kachar** [comment]
There's an error preventing a successful build, @PepiPetrov can you please check it out

```
Type error: Property 'campaignTypes' does not exist on type '{ campaign: { listCampaigns: Endpoint; createCampaign: Endpoint; viewCampaign: (slug: string) => Endpoint; }; campaignType: { listCampaignTypes: Endpoint; }; ... 10 more ...; company: { ...; }; }'. Did you mean 'campaignType'?
```

**Pull request merged**
