### PR TITLE
Fix notification subscription button on My Account (Mobile) #1783

### PR DESCRIPTION
**Pull request by iliyan90**
subscription button on My Account (Mobile)

Closes #{ #1783}

## Screenshots:
Before 
#issue1873
Now
issue1873

### CODE REVIEW

**Review by ani-kalpachka — COMMENTED** [review]
@iliyan90 Good addition! 
It looks good on mobile and desktop, but on tablet screens some elements are misplaced: 

image

If we set the title "Абонаментът ви за получаване на известия e" to be full width it would fix the issue. Could you please check?

**Comment by iliyan90** [comment]
So on tablet active status and button have to be in the same row?

**Comment by ani-kalpachka** [comment]
Checked the designs. Lets leave it like this.
Once the build errors are resolved we can merge it.

**Comment by sashko9807** [comment]
Linter seems to be failing. Try to run `yarn lint`, and push with the formatted linter changes.

**Review by ani-kalpachka — APPROVED** [review]

**Pull request merged**
