### PR TITLE
Add button hover states in the theme to correspond to the UI theme

### PR DESCRIPTION
**Pull request by dimitur2204**
## Motivation and context

The current state of the buttons was pretty random and there were styling on top of the default button stylings. 

I have now changevdthe styles to be in tact with the UI Kit and in my opinion this way they look better.
This is the reference design:
image
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=38%3A3937

There are quite a bit of changes to the theme though and everything has to be looked at by QA if possible since there might be problems that arise from that.

## Screenshots:

| Before              | After              |
| ------------------- | ------------------ |
|image|image|

## Testing

Went through most of the pages and didn't see any blatant problems

### CODE REVIEW

**Comment by dimitur2204** [comment]
Putting @swolf86 as a reviewer to actually confirm if this UI Kit we have in the Figma file is how the buttons are supposed to behave

**Review by kachar — APPROVED** [review]
Outstanding upgrade of  the theme! :rocket: :1st_place_medal: 

Thanks @dimitur2204 

The PR is good by me

**Comment by dimitur2204** [comment]
> Outstanding upgrade of  the theme! :rocket: :1st_place_medal: 
> 
> Thanks @dimitur2204 
> 
> The PR is good by me

You can merge it!

**Comment by swolf86** [comment]
Hi Dimitar, please share a link where we can see the buttons and test all the states 
Thanks

**Comment by kachar** [comment]
@swolf86 You can review some of them on https://dev.podkrepi.bg/campaigns

**Comment by kachar** [comment]
If it's okay I'll share that my personal feeling about this color is not good. Relly wonder if this is the expected color, as it doesn't really match what a "nice color scheme" looks like for me.

image

image

**Comment by dimitur2204** [comment]
> Hi Dimitar, please share a link where we can see the buttons and test all the states Thanks

@swolf86 Ilko pushed the changes to staging check them out here. https://dev.podkrepi.bg/

**Comment by dimitur2204** [comment]
> If it's okay I'll share that my personal feeling about this color. Relly wonder if this is the expected color, as it doesn't really match what a "nice color scheme" looks like for me.
> 
> image
> 
> image

That is the actual color on the UI Kit in Figma. But now when I look at the pages on the Development tab the color is actually different yeah 
image

Maybe we should go with this one. It really does look better

**Comment by swolf86** [comment]
Not sure if you are using the correct dark orange colour 
hover colour is DB6B04
image
image

**Pull request merged**
