### PR TITLE
feat: admin campaign applications

### PR DESCRIPTION
**Pull request by gparlakov**
- show actual applications in the list

### CODE REVIEW

**Review by sashko9807 — CHANGES_REQUESTED** [review]
Please fix the conflicts, and the lint error

**Review by slavcho — APPROVED** [review]

**Comment by gparlakov** [comment]
@slavcho ready

**Comment by sashko9807** [comment]
@gparlakov can this PR be closed?

**Comment by gparlakov** [comment]
@sashko9807 yes.

**Pull request closed without merging**
