### PR TITLE
Remove module-campaigns and docker-compose related service.

### PR DESCRIPTION
**Pull request by preslavgerchev**
Dropped `module-campaigns` folder in favor of the new [repo](https://github.com/podkrepi-bg/module-campaigns/).

I suggest merging this at a convenient time (when there are no active PRs that target campaigns).

@xenry @mayapeneva @kachar @imilchev

### CODE REVIEW

**Comment by mayapeneva** [comment]
I have a branch with the changes on ticket [Feature] Backend: Add Beneficiary Data (#8 in the new repo) and am not sure how to transfer it to the new repo.

**Comment by kachar** [comment]
@mayapeneva First of all please create a PR so the changes are not lost on the way

Otherwise, I'm afraid those changes will have to be moved manually to the new repo

**Comment by preslavgerchev** [comment]
You can create a patch from the git diff and apply this on top of the new repository - then the only thing to do is fix any potential conflicts when applying the patch

**Comment by mayapeneva** [comment]
Thank you @preslavgerchev for you help. All good - the branch is transferred to the new repo

**Pull request merged**
