### PR TITLE
chips added,bug fixes

### PR DESCRIPTION
**Pull request by dzhaniivanov**
Closes  https://github.com/podkrepi-bg/frontend/issues/1430 and replaces old PR: https://github.com/podkrepi-bg/frontend/pull/1524

## Motivation and context
After a discussion with @igoychev  this is the implementation : 
-Financial reports chip is showing conditionally
-reduced white space between title and chips
-bug with showExpensesLink (every time was true) is resolved

## Screenshots:
Screenshot 2023-08-31 195720

### CODE REVIEW

**Review by igoychev — APPROVED** [review]
looks great!

**Comment by swolf86** [comment]
Can we have the chips in blue colour. They are bit hard to read at the moment it might not pass contrast standards 
Can we improve on padding after the chips 
image

**Comment by ani-kalpachka** [comment]
@swolf86 Agreed. I am working on it.

**Comment by ani-kalpachka** [comment]
The changes are added here: https://github.com/podkrepi-bg/frontend/pull/1582

**Pull request merged**
