### PR TITLE
New design for campaign news subscription

### PR DESCRIPTION
**Pull request by RalitsaIlieva**
Closes partially #1550 (campaign news subscription)

## Motivation and context

There is new design that should be implemented

## Screenshots:

image
image
image
image

Before|After
---|---
Paste screenshot|Paste screenshot

### New environment variables:

- [ ] `NEW_ENV_VAR`: env var details

### New or updated dependencies:

Dependency name|Previous version|Updated version|Details
---|---|---|---
`dependency/name`|`v1.0.0`|`v2.0.0`|

### CODE REVIEW

**Review by ani-kalpachka — APPROVED** [review]

**Comment by ani-kalpachka** [comment]
@RalitsaIlieva well done! 
Could you please check the conflicts?

**Comment by ani-kalpachka** [comment]
Is the backend for this task fully completed?

**Comment by RalitsaIlieva** [comment]
> Is the backend for this task fully completed?

No, the backend should be checked. @igoychev is aware of this and promised to check

**Comment by RalitsaIlieva** [comment]
@ani-kalpachka @slavcho nothing has to be done here. The things are merged with the PR about the news subscription. News subscription PR included this campaign news subscription because when I started the work for the news subscription I branched from this one.

**Comment by slavcho** [comment]
Thanks @RalitsaIlieva . Can you suggest what else is needed to move this forward?

**Comment by sashko9807** [comment]
> Thanks @RalitsaIlieva . Can you suggest what else is needed to move this forward? 

I believe this is just a duplicate PR of #1673, and can be closed.

**Comment by ani-kalpachka** [comment]
Thanks! I will close this PR as a duplicate.

**Pull request closed without merging**
