### PR TITLE
Created layout for Coordinator entity

### PR DESCRIPTION
**Pull request by dplamenov**
Created layout for Coordinator entity
Screenshot at Feb 21 15-02-26
Screenshot at Feb 21 15-02-55
Screenshot at Feb 21 15-02-37

### CODE REVIEW

**Review by kachar — APPROVED** [review]
Nice foundation for the coordinators.

In the next iterations we need to focus on:

- removal of `carId` as `car` is not part of podkrepi domain structure
- help the admin enter `personId` by providing a list of people to choose from instead of UUID text input

**Comment by Polina1985** [comment]
Hello again! :)
I am not able to create (add) a new Coordinator. I have entered the admin panel.
Add Coordinator name in administrative panel

See the attached picture.
@dplamenov 

It is tested on PC
windows
Add Cordinator name in administrative panel

Chrome - Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by dplamenov** [comment]
Problem fix is already merged in master branch. #568 @Polina1985

**Comment by Polina1985** [comment]
The problem of not registering a new Coordinator by name still exists.

**Comment by Polina1985** [comment]
InkedAdd Cordinator name in administrative panel_LI

**Comment by Polina1985** [comment]
Inkedcoordinator not_EN_LI

**Comment by Polina1985** [comment]
Yes, it is not shown on dev environment yet. Please, check again and I will retest.

**Comment by kachar** [comment]
@dplamenov @Polina1985 Just deployed the latest master on dev.podkrepi.bg 

Can you please verify it again, thanks for your dedication to the topic

**Comment by dplamenov** [comment]
Already latest changes and fix are on dev.podkrepi.bg @Polina1985 @kachar

**Comment by Polina1985** [comment]
**Guys,**

I have tried to test the functionality of creating a new Coordinator. I am sending you a video recording of the testing:

**Mobile device:** Samsung A22 5G
Android: 11
Chrome Browser - [99.0.4758.101](url)

The same is for PC, Windows, Chrome Browser.

I **am not able to add** **an independent Coordinator name,** just to choose from the existing ones.

https://drive.google.com/file/d/1Tmklfv4pvLejDaq-ygAgSOyzApQrTa1O/view?usp=sharing

**Comment by dplamenov** [comment]
This is by design. To create a coordinator choose from persons list. @Polina1985

**Comment by Polina1985** [comment]
@dplamenov 
Can I find written user stories for each Menus - "Кампании", "Доброволци", "Контакти","Плащания', 'Потребители", etc.
in order to know what functionalities should have each menu? Or to whom to refer - @kachar or @igoychev 
I will check also the Desing - of the administrative panel. But I need to know the manipulations which should have each Menu.

In menu "Координатори' - it is not user - friendly to add Coordinator from Persons.. .for me.

Please, specify, because I do not know how it is designed to work (functionalities).

**Comment by Polina1985** [comment]
Should you try to log in as a user and go to "Потребители" menu?
The info you will see is not relevant at all:
- no users

Only: 
- Field - "Статус"
- Field - "IBAN"
- Field - "Собственик"
- Field - "Вид account"

Therefore, I can not add Coordinator from persons.

**Pull request merged**
