### PR TITLE
Playwright e2e Tests for the Donation Flow 

### PR DESCRIPTION
**Pull request by dimitur2204**
## Motivation and context

Add. a testing of the full flow of the user while donation.
I wanted to the flow for both an unlogged and logged user, but was unable to do that locally. For some reason it was always logged in somehow.

## Testing

**New environment variables**:

- `env var` : env var details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

### CODE REVIEW

**Comment by imilchev** [comment]
I think we are currently not running the mock webhook for payments in our CI. This means that the tests will probably always fail when executed in the pipeline. Please ping me once you have them running locally and I can check what needs to be changed in the CI to make them succeed

**Comment by dimitur2204** [comment]
> I think we are currently not running the mock webhook for payments in our CI. This means that the tests will probably always fail when executed in the pipeline. Please ping me once you have them running locally and I can check what needs to be changed in the CI to make them succeed

I have them running locally, but they are currently failing on the test for a different reason. I will let you know once I get them to the stripe part

**Comment by imilchev** [comment]
Finally, the tests are passing! Feel free to rebase and let's merge this bad boy :shipit:

**Review by kachar — APPROVED** [review]

**Comment by dimitur2204** [comment]
🙌

**Pull request merged**
