### PR TITLE
Add rounded corners to inputs on the theme

### PR DESCRIPTION
**Pull request by dimitur2204**
## Motivation and context

Changed the styling of the inputs in the `muiTheme` we are using. 

The corners of the oneline input fields are now fully round and the corners of the mulitline input are more round than they were before

## Screenshots:

| Before              | After              |
| ------------------- | ------------------ |
|image|image|

## Testing

Went through many of the pages and didn't find any bugs whatsoever 🚀!

### CODE REVIEW

**Review by kachar — COMMENTED** [review]
@dimitur2204 Do we need to revoke custom border radius styles from any inputs or buttons so the theme can kick in everywhere?

**Comment by dimitur2204** [comment]
> @dimitur2204 Do we need to revoke custom boder radius styles from any inputs or buttons so the theme can kick in everywhere?

What exactly do you need

**Comment by kachar** [comment]
@dimitur2204 If we use custom border style on some inputs or buttons, the newly added global values won't override the local styles.

So I wonder if we need to revise the usage of `borderRadius` in the whole project?

**Review by kachar — APPROVED** [review]
I've reviewed every usage of `borderRadius` and it seems none of them are related to inputs.

I'm not a particular fan of the so rounded inputs, but  let's roll with this update :rocket:

**Comment by dimitur2204** [comment]
> 

I am not particularly a fan too, but design said that's how the UI Kit is. 

For the border radiuses being repeated everywhere I would change that once the changes to the theme from #742 get merged into master some time in the future. Hopefully I remember :).

**Pull request merged**
