### PR TITLE
try to migrate dataGrid and datePicker to v6

### PR DESCRIPTION
**Pull request by dzhaniivanov**
## Motivation and context

related to #1440

remove the old pageSize and onPageSizeChange props and replace them with the new one

https://mui.com/x/migration/migration-data-grid-v5/

i think for the first  time making this kind of entire deps changing and I am open to suggestions from experienced collegues.i will continue with some typing

### CODE REVIEW

**Review by ani-kalpachka — APPROVED** [review]

**Review by ani-kalpachka — APPROVED** [review]

**Comment by ani-kalpachka** [comment]
@dzhaniivanov Could you please check the build issue?

**Comment by igoychev** [comment]
hey Dzhani, would you have time to complete this PR?

**Comment by dzhaniivanov** [comment]
> hey Dzhani, would you have time to complete this PR?

hello, I tell Ani to move it to test colleagues for regression I think it is ready for testing(I will fix the bugs after the test, no problem)

**Review by igoychev — CHANGES_REQUESTED** [review]
great work overall for upgrading us to next version!

I've tested and there are a few things to fix before marking it complete - check my comments below.

**Comment by dzhaniivanov** [comment]
> great work overall for upgrading us to next version!
> 
> I've tested and there are a few things to fix before marking it complete - check my comments below.

thanks for reviewing,it's done

**Review by igoychev — APPROVED** [review]

**Pull request merged**
