### PR TITLE
CI stripe webhook

### PR DESCRIPTION
**Pull request by imilchev**
Starts stripe webhook before playwright tests

### CODE REVIEW

**Comment by dimitur2204** [comment]
There are some changes to the donation flow from #1133. I will take a look and change the tests. You can remove the test files from this PR!

**Comment by imilchev** [comment]
> There are some changes to the donation flow from #1133. I will take a look and change the tests. You can remove the test files from this PR! You can rebase your changes on top of master

This PR should merge to #1110 I just haven't updated the base. I can do that now

**Review by dimitur2204 — APPROVED** [review]
Looks good to me, but you might want to wait for @kachar :)

**Comment by imilchev** [comment]
> Looks good to me, but you might want to wait for @kachar :)

It's still failing 😆 I am figuring out the stripe permissions this thing needs. After that it should pass and then we can merge it into your branch

**Pull request merged**
