### PR TITLE
Fixed width of images on homepage

### LINKED ISSUE #1186: [Bug] The images on Homepage are not responsive
**Describe the bug**
The images on Homepage are not responsive.

**To Reproduce**
1. Go to 'Homepage'.
3. Scroll down to 'Кой стой зад Подкрепи.бг' and 'Присъединете се зад Подкрепи.бг'.
4. Switch to mobile view.
5. Observe the images.

**Expected behavior**
The images on Homepage are responsive and adaptive for each resolution.

**Screenshots**

### PR DESCRIPTION
**Pull request by pshumareva**
The images on Homepage are not responsive

Closes #1186 

## Motivation and context

Design was broken.

Images overflow the container.

With a nextjs/image property.

## Screenshots:

Before 
before
After
after

### New environment variables:

- [ ] `NEW_ENV_VAR`: env var details

### New or updated dependencies:

Dependency name|Previous version|Updated version|Details
---|---|---|---
`dependency/name`|`v1.0.0`|`v2.0.0`|

### CODE REVIEW

**Review by ani-kalpachka — APPROVED** [review]

**Review by ani-kalpachka — CHANGES_REQUESTED** [review]
@pshumareva, thanks for your effort! :) 

The 'layout' property is deprecated and causes warnings. Could we find another solution? For example the following should work:
  width: 100%;
  height: auto;

**Comment by kachar** [comment]
@pshumareva You can read more about the changes applied with Next 13 at https://nextjs.org/docs/api-reference/next/legacy/image

On this link you can find snippets with migration ideas: https://nextjs.org/docs/advanced-features/codemods#next-image-experimental-experimental

**Comment by dimitur2204** [comment]
> The 'layout' property solves the problem but it is deprecated and causes warnings. Could we find another solution? For example the following should work: width: 100%; height: auto;
> 
NextJS will complain about adding width: 100%; like that to the image. Maybe `maxWidth: 100%` will be the solution.

**Comment by pshumareva** [comment]
I'll have a look at it today.

**Comment by ani-kalpachka** [comment]
Closing this PR since the issue is fixed with https://github.com/podkrepi-bg/frontend/pull/1233.

**Pull request closed without merging**
