### PR TITLE
1235 - implement a footer component to improve general HTML semantics.

### LINKED ISSUE #1235: [Feature] Improve HTML semantics - implement a <footer> element
HTML has several semantic elements that define the different parts of a web page.

img_sem_elements

Currently we are using a `<div>` element instead of `<footer>`.

Let's make a little effort to fix that and improve general code semantics.

### PR DESCRIPTION
**Pull request by kabaivanov**
This is a tiny effort to improve general HTML code semantics by implementing a footer HTLM element.

Closes #1235 

## Motivation and context

HTML has several semantic elements that define the different parts of a web page.

img_sem_elements

`<footer>` is one of them, and we didn't have it.

### Affected urls

Sitewide

### CODE REVIEW

**Review by ani-kalpachka — APPROVED** [review]

**Review by kachar — APPROVED** [review]

**Comment by kachar** [comment]
@kabaivanov Looks like the next build is failing regarding the new property. Do you think you can look into the problem?

**Comment by ani-kalpachka** [comment]
To resolve the build failure you can set the type of the component in Footer.styled.tsx:

`export const Root = styled('footer')(() => ({` ...

and remove the component property.

**Comment by kabaivanov** [comment]
> To resolve the build failure you can set the type of the component in Footer.styled.tsx:
> 
> `export const Root = styled('footer')(() => ({` ...
> 
> and remove the component property.

@ani-kalpachka just committed an update following your guidelines but tests still seem to fail :-\

**Review by dimitur2204 — APPROVED** [review]

**Comment by ani-kalpachka** [comment]
You can try to delete the maxWidth and disableGutters properties of the Root component. The wrapper component which is inside it takes care of the maxWidth. 
Also please rebase the master branch. 
This has to resolve the build issues or at least the one what is happening because of the maxWidth property.

**Pull request merged**
