### PR TITLE
1254 - add campaign title to certificate

### LINKED ISSUE #1254: [Bug] All generated donation certificates show Podkrepi.bg as beneficiary, no matter of donation recipient.
### Describe the Bug

After making a donation the user can go to their user account panel and review his past donations.
For each donation the user makes, there is an automatically generated donation certificate, which is .pdf downloadable.

Currently all certificates show Podkrepi.bg as beneficiary. This is wrong.

Screenshot 2022-12-13 at 22 25 26

### To Reproduce

Make a donation, go to your user account panel and review your donations. 
Find the Certificate and download it.
Review.

### Expected Behavior

All certificates should include the title of the actual campaign as a the donation beneficiary. 

Donation certificates that show Podkrepi.bg as beneficiary should only be emitted on actual donations for Podkrepi.bg

### PR DESCRIPTION
**Pull request by dimitur2204**
Closes #1254 

## Motivation and context
Before our certificate had only "за дейността на сдружението." as an indication of where the donation was forwarded to.

I had to do some request gymnastics to get: donation -> vaultId -> vaultResponse -> campaignId -> campaignResponse to pass it to the `<Certificate />`. If someone knows an easier way would be appreciated!

## Screenshots:

Before|After
---|---
image|image

### Steps to test
Make a donation
Go to the profile page
Click download certificate
### Affected urls

http://localhost:3040/api/pdf/certificate/:donationId

### CODE REVIEW

**Review by kachar — COMMENTED** [review]
@dimitur2204 There are a couple of things to consider: 

1. We can improve the backend response, instead of doing two more API calls on the frontend during the certificate generation
2. The title of the campaign can be very very long which may break the PDF layout.


I'll prepare a draft with the updates for point 1, and would like to ask you for ideas on point 2.

See https://github.com/podkrepi-bg/api/pull/405

I'll push a commit on your branch that accommodates the API changes

**Review by kachar — APPROVED** [review]

**Comment by kachar** [comment]
@dimitur2204 Do you feel we need to add anything else to the PR?

**Comment by kachar** [comment]
API PR https://github.com/podkrepi-bg/api/pull/405 got merged

**Comment by dimitur2204** [comment]
> API PR [podkrepi-bg/api#405](https://github.com/podkrepi-bg/api/pull/405) got merged

Good job on all the changes and the notice of the styling problem. I think it's good! I will merge

**Pull request merged**
