### PR TITLE
Custom auth forms

### LINKED ISSUE #371: Create custom authentication
The motivation here is to reduce the friction between different systems and provide smooth UX in a single application.

At the moment users are being sent to https://keycloak.podkrepi.bg/auth/realms/webapp-dev/protocol/openid-connect/auth in order to login to https://podkrepi.bg and this creates confusion.

Our API layer now supports authentication via `/login` and `/register` endpoints (Check [swagger](https://dev.podkrepi.bg/docs/))

What needs to be done:

- [ ] Replace Keycloak authentication screens (login & registration) with internal forms
  - [ ] Replace handler for login form
  - [ ] Replace handler for registration form
  - [ ] Handle cookie storage (either manually on the frontend or via XHR cookie by the backend)
- [ ] Recognize the session cookie and provide it to the `SSRKeycloakProvider`

### PR DESCRIPTION
**Pull request by atanasster**
closes #371 

## Motivation and context

create custom authentication mechanism and related forms

## Screenshots:

Login form:

| Before              | After              |
| ------------------- | ------------------ |
| grab208 | grab209|

Registration Form
| Before              | After              |
| ------------------- | ------------------ |
|grab210|grab211|

## Testing

Test that the registration and login backend apis are not public

**New environment variables**:

CSRF_SECRET 

**New dependencies**:

"next-csrf": "beta", <-- this version has the cookie policy for csrf 

**Removed dependencies**:
"axios-hooks"
"lru-cache"

### CODE REVIEW

**Comment by atanasster** [comment]
Експериментално nextjs api routes за login i register: https://github.com/podkrepi-bg/frontend/blob/custom-auth-forms/src/pages/api/login.ts
Те действат като прокси за истинските заявки към бакенда. T.e. Login и Register отиват към /api/login и /api/register вместо към съотвените api на бакенда.
- По принцип nextjs api routes за защитени с cors same origin policy (само заявки от същия сайт са приети)
- Добавих и cookie policy за csrf защита за тези две api (въпреки че може и само по-горната cors защита да е достатъчна)
- Така тези защити биха работили, а истинското api на бакенда можем да го защитим със секретен АPI key: https://www.stewright.me/2021/03/add-header-api-key-to-nestjs-rest-api/ и ще бъде достъпен само за фронтенд nextjs сървъра
---
Не съм сигурен защо от nextjs бакенда не може да се достигне local бакенда ${process.env.API_URL}/api/login (timeout), въпреки че виждам http://localhost:3040 е добавен като webOrigins.
Също https://dev.podkrepi.bg/api/login дава грешка 500. 
Та засега нещата работят само на https://podkrepi.bg/api/login и отговаря с jwt 
---

**Comment by kachar** [comment]
Custom Keycloak Forms UI https://github.com/InseeFrLab/keycloakify

**Comment by kachar** [comment]
Adding label "on hold" as we're exploring another solution with customized look'n'feel of the default keycloak login/register form instead of having the whole authentication mechanism inside the frontend. This might help us iterate faster and still keep certain functionalities like checking the nested permissions from the jwt token.

**Comment by kachar** [comment]
Closing this PR as we'll stick with Keycloak authentication forms with a custom design.

All other solutions are quite complex and will require many many more hours to be polished and functional. In a perfect scenario, we would have enough people to complete it, but at this point in time, we don't have that luxury and need to stick to a more simple solution.

The current Keycloak solution is sufficient both on the backend and frontend as it provides ways to check for the permissions based on JWT token without custom implementations.

@atanasster Thanks for the energy and brainpower you've put into this PR.

image

**Pull request closed without merging**
